#!/usr/bin/env ruby
# =============================================================================
# gen_dashboard.rb — write the static SITE_HEALTH.md from the triage outputs
# -----------------------------------------------------------------------------
# Reads _data/health/summary.yml + queue.json and renders a committed
# SITE_HEALTH.md so the repo/PR view shows site health at a glance (the Liquid
# version for visitors lives at /docs/health/). Run after build_queue.rb.
#   ruby scripts/triage/gen_dashboard.rb
# =============================================================================
require_relative '_lib'

sfile = File.join(Triage::HEALTH, 'summary.yml')
qfile = File.join(Triage::HEALTH, 'queue.json')
abort 'run build_queue.rb first (no summary.yml/queue.json)' unless File.exist?(sfile) && File.exist?(qfile)

s = LH.yload(LH.read(sfile)) || {}
q = JSON.parse(LH.read(qfile))

out = +"<!-- generated by scripts/triage/gen_dashboard.rb — do not edit by hand -->\n"
out << "# Site Health\n\n"
out << "_Last triage: #{s['generated_at']}_  ·  **#{s['queue_size']}** item(s) in the queue.\n"
out << "_Analytics not yet connected — ranking by severity only._\n" if s['analytics_stale']
out << "\n## By severity\n\n"
(s['by_severity'] || {}).sort.each { |k, v| out << "- **#{k}**: #{v}\n" }
out << "\n## By route\n\n"
(s['by_route'] || {}).sort.each { |k, v| out << "- **#{k}**: #{v}\n" }
out << "\n## Top of the queue\n\n"
out << "| score | sev | type | where | route | repo |\n|---|---|---|---|---|---|\n"
q.first(20).each do |i|
  where = (i['url_path'] && !i['url_path'].empty?) ? i['url_path'] : i['file']
  out << "| #{i['score']} | #{i['severity']} | #{i['type']} | `#{where}` | #{i['route']} | #{i['repo']} |\n"
end
out << "\n_Generated from `_data/health/`. The live version is at_ "\
       "[/docs/health/](https://lifehacker.dev/docs/health/)_. Don't edit this file by hand._\n"

File.write(File.join(LH::ROOT, 'SITE_HEALTH.md'), out)
puts "[gen_dashboard] wrote SITE_HEALTH.md (#{q.size} queue items)"
