#!/usr/bin/env bash
# =============================================================================
# check-todos.sh — scan the repo for follow-up tags and report them.
# -----------------------------------------------------------------------------
# Catches the conventional markers (case-sensitive, so prose "fix"/"prefix" is
# ignored): TODO FIXME FIX HACK XXX BUG PLACEHOLDER.
#
# Usage:
#   scripts/check-todos.sh            # print a Markdown report to stdout
#   scripts/check-todos.sh --write    # also (re)write TODO.md
#   scripts/check-todos.sh --strict   # exit 1 if any FIXME exists (CI blocker)
# =============================================================================
set -uo pipefail

ROOT="${CLAUDE_PROJECT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
WRITE=0; STRICT=0
for a in "$@"; do
  case "$a" in --write) WRITE=1;; --strict) STRICT=1;; esac
done

MARKERS='TODO|FIXME|FIX|HACK|XXX|BUG|PLACEHOLDER'
# Match the ANNOTATED form only — marker immediately followed by ":" or "(scope)".
# This is the convention (TODO:, FIX(upstream):) and avoids false positives like
# `rg TODO` (a search example), `HACK-001` (an id), or prose mentioning the words.
# Skip build output, vendored dirs, the generated report, and this scanner itself.
HITS="$(cd "$ROOT" && grep -rEn "\b($MARKERS)(\(|:)" \
  --include='*.md' --include='*.markdown' --include='*.html' \
  --include='*.yml' --include='*.yaml' --include='*.sh' \
  --include='*.scss' --include='*.css' --include='*.js' --include='*.rb' \
  --include='*.json' \
  . 2>/dev/null \
  | grep -vE '/(_site|vendor|node_modules|\.git|\.jekyll-cache|\.bundle)/' \
  | grep -vE '(^|/)(TODO\.md|CHANGELOG\.md):' \
  | grep -vE '/scripts/check-todos\.sh:' \
  | grep -vE '/scripts/test-[^/]*\.sh:' \
  | grep -vE '/pages/_docs/ci-cd\.md:' \
  | sort)"

total="$(printf '%s' "$HITS" | grep -c . || true)"

render() {
  echo "# TODO — follow-ups tagged in the repo"
  echo
  echo "Auto-generated by \`scripts/check-todos.sh\`. Markers: \`TODO FIXME FIX HACK XXX BUG PLACEHOLDER\`."
  echo "Regenerate with \`make todo\` (or \`scripts/check-todos.sh --write\`)."
  echo
  if [[ "$total" -eq 0 ]]; then
    echo "_Nothing tagged. The loop is closed._"
    return
  fi
  echo "**$total open follow-up(s).**"
  echo
  local m
  for m in TODO FIXME FIX HACK XXX BUG PLACEHOLDER; do
    local rows; rows="$(printf '%s\n' "$HITS" | grep -E "\b$m(\(|:)" || true)"
    [[ -z "$rows" ]] && continue
    local c; c="$(printf '%s' "$rows" | grep -c .)"
    echo "## $m ($c)"
    echo
    printf '%s\n' "$rows" | while IFS= read -r row; do
      row="${row#./}"
      local loc txt
      loc="$(printf '%s' "$row" | cut -d: -f1-2)"
      txt="$(printf '%s' "$row" | cut -d: -f3- \
              | sed -E 's/^[[:space:]]*([#<!/*-]+[[:space:]]*)?//; s/[[:space:]]+$//' \
              | cut -c1-110)"
      echo "- \`$loc\` — $txt"
    done
    echo
  done
}

REPORT="$(render)"
printf '%s\n' "$REPORT"

if [[ "$WRITE" -eq 1 ]]; then
  printf '%s\n' "$REPORT" >"$ROOT/TODO.md"
  echo "(wrote TODO.md)" >&2
fi

if [[ "$STRICT" -eq 1 ]]; then
  fixmes="$(printf '%s\n' "$HITS" | grep -cE ':FIXME(\(|:)' || true)"
  [[ "${fixmes:-0}" -gt 0 ]] && { echo "check-todos: $fixmes FIXME blocker(s) present" >&2; exit 1; }
fi
exit 0
