#!/usr/bin/env bash
# =============================================================================
# test-session-scribe.sh — offline, deterministic tests for the Session Scribe.
# -----------------------------------------------------------------------------
# No network, no real `claude` call: we inject a fake writer via SCRIBE_WRITER_CMD
# and write to a temp dir via SCRIBE_DISPATCH_DIR, in dry-run (no git/PR).
# Run: scripts/test-session-scribe.sh   (exits non-zero if any check fails)
# =============================================================================
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIBE="$SCRIPT_DIR/session-scribe.sh"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

PASS=0; FAIL=0
ok() { printf '  \033[32m✓\033[0m %s\n' "$1"; PASS=$((PASS+1)); }
no() { printf '  \033[31m✗\033[0m %s\n' "$1"; FAIL=$((FAIL+1)); }

# Fixtures: a "real" transcript (>= SCRIBE_MIN_LINES) and a trivial one.
BIG="$TMP/big.jsonl";   for i in $(seq 1 40); do printf '{"type":"message","i":%s}\n' "$i"; done >"$BIG"
SMALL="$TMP/small.jsonl"; for i in $(seq 1 5);  do printf '{"i":%s}\n' "$i"; done >"$SMALL"
OUT="$TMP/dispatches"

# Fake writer emits an article body containing an H1 and a fake leaked token.
STUB='printf "# Sample Session Title\n\nWe configured a thing and it broke once.\nLeaked ghp_ABCDEFGHIJKLMNOPQRSTUVWX in here by mistake.\n\n## Takeaways\n- It works now.\n"'

export SCRIBE_DISPATCH_DIR="$OUT" SCRIBE_DRY_RUN=1 SCRIBE_WRITER_CMD="$STUB"

echo "== Session Scribe tests =="

# 1. Recursion guard — must do nothing when the guard env is set.
rm -rf "$OUT"; mkdir -p "$OUT"
CLAUDE_SESSION_SCRIBE=1 bash "$SCRIBE" write --session aaaaaaaa1111 --transcript "$BIG" >/dev/null 2>&1
[ -z "$(ls -A "$OUT" 2>/dev/null)" ] && ok "recursion guard: no dispatch written" || no "recursion guard wrote a file"

# 2. Trivial-session skip.
rm -rf "$OUT"; mkdir -p "$OUT"
bash "$SCRIBE" write --session bbbbbbbb2222 --transcript "$SMALL" >/dev/null 2>&1
[ -z "$(ls -A "$OUT" 2>/dev/null)" ] && ok "trivial session skipped" || no "trivial session produced a file"

# 3. Happy path — file + frontmatter + scrub + H1 handling.
rm -rf "$OUT"; mkdir -p "$OUT"
bash "$SCRIBE" write --session cccccccc3333 --transcript "$BIG" >/dev/null 2>&1
F="$(ls "$OUT"/*.md 2>/dev/null | head -1)"
[ -n "$F" ] && ok "dispatch file written" || no "no dispatch file produced"
if [ -n "$F" ]; then
  grep -q 'collection: dispatches'        "$F" && ok "frontmatter: collection"      || no "missing collection"
  grep -q 'auto_generated: true'          "$F" && ok "frontmatter: auto_generated"  || no "missing auto_generated"
  grep -q 'title: "Sample Session Title"' "$F" && ok "title taken from H1"          || no "title not from H1"
  grep -q 'Auto-generated by the'         "$F" && ok "auto-generated banner present"|| no "missing banner"
  grep -q '\[REDACTED\]'                  "$F" && ok "leaked token scrubbed"         || no "secret NOT scrubbed"
  grep -q 'ghp_ABCDEFGHIJKLMNOPQRSTUVWX'  "$F" && no "raw token still present"       || ok "raw token absent"
  grep -qE '^# Sample Session Title'       "$F" && no "H1 not stripped from body"     || ok "H1 stripped from body"
fi

# 4. Idempotency — second run for the same session adds no second file.
bash "$SCRIBE" write --session cccccccc3333 --transcript "$BIG" >/dev/null 2>&1
CNT="$(ls "$OUT"/*cccccccc.md 2>/dev/null | wc -l | tr -d ' ')"
[ "$CNT" = "1" ] && ok "idempotent (one dispatch per session)" || no "idempotency broke ($CNT files)"

# 5. Hook subcommand respects the recursion guard (no crash, no file).
rm -rf "$OUT"; mkdir -p "$OUT"
printf '{"session_id":"dddddddd4444","transcript_path":"%s","reason":"clear"}' "$BIG" \
  | CLAUDE_SESSION_SCRIBE=1 bash "$SCRIBE" hook >/dev/null 2>&1
RC=$?
[ "$RC" = "0" ] && ok "hook honors recursion guard (exit 0)" || no "hook returned $RC under guard"

# 6. Disabled mode writes nothing.
rm -rf "$OUT"; mkdir -p "$OUT"
SCRIBE_DISABLED=1 bash "$SCRIBE" write --session eeeeeeee5555 --transcript "$BIG" >/dev/null 2>&1
[ -z "$(ls -A "$OUT" 2>/dev/null)" ] && ok "SCRIBE_DISABLED=1 writes nothing" || no "disabled mode wrote a file"

echo "== $PASS passed, $FAIL failed =="
[ "$FAIL" -eq 0 ]
